[package]
name = "emu6502"
version = "0.1.0"
edition = "2021"

[lib]
name = "libemu6502"
path = "src/lib.rs"

[[bin]]
name = "emu6502"
path = "src/main.rs"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
