[package]
name = "x86"
version = "0.1.0"
edition = "2021"

[lib]
name = "libemux86"
path = "src/lib.rs"

[[bin]]
name = "emux86"
path = "src/main.rs"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
